### ISSUE TITLE
Move->Trade->Cancel->Move Again

### ISSUE THREAD

**Issue by BadaroThiago** [Grimmys/rpg_tactical_fantasy_game#17] opened 2020-12-04 14:42 UTC
It is possible to move a character to a position next to an ally, initiate a trade, trade itens/money, cancel menu and that character is returned to his initial position, but the trade is already done and he can move again. I suggest that after trades, the player loses the ability to cancel the menu until character has attacked or choose to wait.

**Comment by Grimmys** [comment] 2020-12-04 18:18
I was already aware of this issue, the problem is not that easy to correct. I think it should be possible to cancel trade when it has only been initiated.

Anyway, I think about it, I have other priorities for the moment but thank you for creating this issue. 👍

**Comment by VSneaxV** [comment] 2023-03-07 21:26
Rip

**Comment by JimZhouZZY** [comment] 2023-07-31 09:24
It seems that I cannot reproduce the bug on trading items. #37 Fixed the bug well.
But I did reproduced it when sending gold. (See the video)
https://github.com/Grimmys/rpg_tactical_fantasy_game/assets/140597003/181f4479-9f48-442d-a937-45723ca2e890
Ill try work for it.

**Comment by Grimmys** [comment] 2023-08-06 10:52
Thanks for investigating and fixing the issue @JimZhouZZY 

Closing it as fixed by #65

**Closed by Grimmys** 2023-08-06 10:52 UTC
Labels: bug
